### ISSUE TITLE
dpdk-pdump: vdev creation failed: Driver can not attach the device 

### ISSUE THREAD

**Issue by rong00gle** [cloudius-systems/dpdk#2]
when running the pdump getting the following error
my system config
hardware= dell poweredge r730
CPU= dual socket (xeon e5 2697a)
OS=CentOS 7
dpdk version=16.11.1
interface getting traffic=port0
NIC=intel x710 DA/SFP+
hugepage size=1G
number of hugepage=16
error copy
> [root@localhost pdump]# ./dpdk-pdump -- --pdump 'port=0,queue=*,rx-dev=test.pcap'
EAL: Detected 64 lcore(s)
EAL: Probing VFIO support...
EAL:   cannot connect to primary process!
EAL: VFIO support could not be initialized
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: PCI device 0000:83:00.0 on NUMA socket 1
EAL:   probe driver: 8086:1572 net_i40e
EAL: PCI device 0000:83:00.1 on NUMA socket 1
EAL:   probe driver: 8086:1572 net_i40e
EAL: no driver found for net_pcap_rx_0
EAL: Driver cannot attach the device (net_pcap_rx_0)
EAL: Error - exiting with code: 1
  Cause: vdev creation failed:create_mp_ring_vdev:736

>

**Comment by avikivity** [comment]
Please report dpdk problems to the dpdk mailing list.
